# Configuration for the repo
REPO:
  NAME: slacktools
  URL: https://github.com/barretobrock/${REPO_NAME}
  GIT_URL: git+${REPO_URL}.git#egg=${REPO_NAME}
  DIR: ${HOME}/extras/${REPO_NAME}
  VENV: ${HOME}/venvs/slackspace/bin/python
  DESC: A common library for working with Slack
  DEPS:
    - git+https://github.com/barretobrock/kavalkilu.git#egg=kavalkilu
